In [1]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import confusion_matrix, classification_report

---

## Split the Data into Training and Testing Sets

### Step 1: Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

In [2]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
lending_path = Path("./Resources/lending_data.csv")
lending_df = pd.read_csv(lending_path)

# Review the DataFrame
lending_df

loan_size  interest_rate  borrower_income  debt_to_income  \
0        10700.0          7.672            52800        0.431818   
1         8400.0          6.692            43600        0.311927   
2         9000.0          6.963            46100        0.349241   
3        10700.0          7.664            52700        0.430740   
4        10800.0          7.698            53000        0.433962   
...          ...            ...              ...             ...   
77531    19100.0         11.261            86600        0.653580   
77532    17700.0         10.662            80900        0.629172   
77533    17600.0         10.595            80300        0.626401   
77534    16300.0         10.068            75300        0.601594   
77535    15600.0          9.742            72300        0.585062   

       num_of_accounts  derogatory_marks  total_debt  loan_status  
0                    5                 1       22800            0  
1                    3                 0       13600            0  
2                    3                 0       16100            0  
3                    5                 1       22700            0  
4                    5                 1       23000            0  
...                ...               ...         ...          ...  
77531               12                 2       56600            1  
77532               11                 2       50900            1  
77533               11                 2       50300            1  
77534               10                 2       45300            1  
77535                9                 2       42300            1  

[77536 rows x 8 columns]

### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

In [3]:
# Separate the data into labels and features

# Separate the y variable, the labels
y = lending_df["loan_status"]

# Separate the X variable, the features
X = lending_df.drop(columns="loan_status")

In [4]:
# Review the y variable Series
y[:5]

0    0
1    0
2    0
3    0
4    0
Name: loan_status, dtype: int64

In [5]:
# Review the X variable DataFrame
X.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  
0                 1       22800  
1                 0       13600  
2                 0       16100  
3                 1       22700  
4                 1       23000

In [6]:
y.value_counts()

loan_status
0    75036
1     2500
Name: count, dtype: int64

### Step 3: Split the data into training and testing datasets by using `train_test_split`.

In [7]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
# Assign a random_state of 1 to the function
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

In [8]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
logistic_regression = LogisticRegression(solver='lbfgs', random_state=1)
logistic_regression

# Fit the model using training data
LR_model = logistic_regression.fit(X_train,y_train)

### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [9]:
# Make a prediction using the testing data
predictions = logistic_regression.predict(X_test)
LR_predictions = pd.DataFrame({"Predictions": predictions, "Actual":y_test}).reset_index(drop=True)
LR_predictions

Predictions  Actual
0                0       0
1                1       1
2                0       0
3                0       0
4                0       0
...            ...     ...
19379            0       0
19380            0       0
19381            0       0
19382            0       0
19383            0       0

[19384 rows x 2 columns]

### Step 3: Evaluate the model’s performance by doing the following:

* Generate a confusion matrix.

* Print the classification report.

In [10]:
# Generate a confusion matrix for the model
confusion_matrix(predictions,y_test)


array([[18673,    32],
       [   86,   593]], dtype=int64)

In [11]:
# Print the classification report for the model
print(classification_report(predictions,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     18705
           1       0.95      0.87      0.91       679

    accuracy                           0.99     19384
   macro avg       0.97      0.94      0.95     19384
weighted avg       0.99      0.99      0.99     19384



### Step 4: Answer the following question.

**Question:** How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** The logistic regression model was 94% accurate at predicting the healthy vs high-risk loan labels

---

# Use original data with RandomForestClassifier

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score


In [13]:
# make a copy of the data to use
lending_SVM = lending_df.copy()
lending_SVM

loan_size  interest_rate  borrower_income  debt_to_income  \
0        10700.0          7.672            52800        0.431818   
1         8400.0          6.692            43600        0.311927   
2         9000.0          6.963            46100        0.349241   
3        10700.0          7.664            52700        0.430740   
4        10800.0          7.698            53000        0.433962   
...          ...            ...              ...             ...   
77531    19100.0         11.261            86600        0.653580   
77532    17700.0         10.662            80900        0.629172   
77533    17600.0         10.595            80300        0.626401   
77534    16300.0         10.068            75300        0.601594   
77535    15600.0          9.742            72300        0.585062   

       num_of_accounts  derogatory_marks  total_debt  loan_status  
0                    5                 1       22800            0  
1                    3                 0       13600            0  
2                    3                 0       16100            0  
3                    5                 1       22700            0  
4                    5                 1       23000            0  
...                ...               ...         ...          ...  
77531               12                 2       56600            1  
77532               11                 2       50900            1  
77533               11                 2       50300            1  
77534               10                 2       45300            1  
77535                9                 2       42300            1  

[77536 rows x 8 columns]

In [14]:
y2 = lending_SVM["loan_status"].values.reshape(-1,1)
y2

array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [1]], dtype=int64)

In [15]:
X2 = lending_df.drop(columns="loan_status")
X2

loan_size  interest_rate  borrower_income  debt_to_income  \
0        10700.0          7.672            52800        0.431818   
1         8400.0          6.692            43600        0.311927   
2         9000.0          6.963            46100        0.349241   
3        10700.0          7.664            52700        0.430740   
4        10800.0          7.698            53000        0.433962   
...          ...            ...              ...             ...   
77531    19100.0         11.261            86600        0.653580   
77532    17700.0         10.662            80900        0.629172   
77533    17600.0         10.595            80300        0.626401   
77534    16300.0         10.068            75300        0.601594   
77535    15600.0          9.742            72300        0.585062   

       num_of_accounts  derogatory_marks  total_debt  
0                    5                 1       22800  
1                    3                 0       13600  
2                    3                 0       16100  
3                    5                 1       22700  
4                    5                 1       23000  
...                ...               ...         ...  
77531               12                 2       56600  
77532               11                 2       50900  
77533               11                 2       50300  
77534               10                 2       45300  
77535                9                 2       42300  

[77536 rows x 7 columns]

In [16]:
# Splitting into Train and Test sets
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, random_state=78)

Use the `StandardScaler` to scale the features data, remember that only `X2_train` and `X2_testing` DataFrames should be scaled.

In [17]:
# Create the StandardScaler instance
scaler = StandardScaler()

In [18]:
# Fit the Standard Scaler with the training data
X_scaler = scaler.fit(X2_train)

In [19]:
# Scale the training data
X_train_scaled = X_scaler.transform(X2_train)
X_test_scaled = X_scaler.transform(X2_test)

In [20]:
# Create the random forest classifier instance
rf_model = RandomForestClassifier(n_estimators=500, random_state=278)

In [21]:
# Fit the model and use .ravel()on the "y_train" data. 
rf_model = rf_model.fit(X_train_scaled, y2_train.ravel())

In [22]:
# Making predictions using the testing data
predictions = rf_model.predict(X_test_scaled)

In [23]:
# Calculating the confusion matrix
cm = confusion_matrix(y2_test, predictions)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
)

# Calculating the accuracy score
acc_score = accuracy_score(y2_test, predictions)

In [24]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y2_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0        18691           93
Actual 1           71          529

Accuracy Score : 0.9915394139496492
Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     18784
           1       0.85      0.88      0.87       600

    accuracy                           0.99     19384
   macro avg       0.92      0.94      0.93     19384
weighted avg       0.99      0.99      0.99     19384



# Use KNeighborsClassifier

In [25]:
from sklearn.cluster import KMeans
from warnings import simplefilter
simplefilter(action='ignore', category=FutureWarning)
from sklearn.neighbors import KNeighborsClassifier


In [26]:
lending_knn = lending_df.copy()
lending_knn

loan_size  interest_rate  borrower_income  debt_to_income  \
0        10700.0          7.672            52800        0.431818   
1         8400.0          6.692            43600        0.311927   
2         9000.0          6.963            46100        0.349241   
3        10700.0          7.664            52700        0.430740   
4        10800.0          7.698            53000        0.433962   
...          ...            ...              ...             ...   
77531    19100.0         11.261            86600        0.653580   
77532    17700.0         10.662            80900        0.629172   
77533    17600.0         10.595            80300        0.626401   
77534    16300.0         10.068            75300        0.601594   
77535    15600.0          9.742            72300        0.585062   

       num_of_accounts  derogatory_marks  total_debt  loan_status  
0                    5                 1       22800            0  
1                    3                 0       13600            0  
2                    3                 0       16100            0  
3                    5                 1       22700            0  
4                    5                 1       23000            0  
...                ...               ...         ...          ...  
77531               12                 2       56600            1  
77532               11                 2       50900            1  
77533               11                 2       50300            1  
77534               10                 2       45300            1  
77535                9                 2       42300            1  

[77536 rows x 8 columns]

In [27]:
# Create a list to store inertia values
inertia = []

# Create a list to store the values of k
k = list(range(1, 11))

In [28]:
for i in k:
    k_model = KMeans(n_clusters=i, random_state=1)
    k_model.fit(lending_knn)
    inertia.append(k_model.inertia_)

In [29]:
# Create a Dictionary that holds the list values for k and inertia
elbow_data = {"k": k, "inertia": inertia}

# Create a DataFrame using the elbow_data Dictionary
df_elbow = pd.DataFrame(elbow_data)

# Review the DataFrame
df_elbow.head()

k       inertia
0  1  1.120769e+13
1  2  3.586398e+12
2  3  1.438449e+12
3  4  8.555935e+11
4  5  6.078136e+11

In [30]:
# Plot the DataFrame
import hvplot.pandas

df_elbow.hvplot.line(
    x="k",
    y="inertia",
    title="Elbow Curve",
    xticks=k
)

:Curve   [k]   (inertia)

In [31]:
# Split target column from dataset
y3 = lending_knn['loan_status']
X3 = lending_knn.drop(columns='loan_status')

In [42]:
y3.value_counts()

loan_status
0    75036
1     2500
Name: count, dtype: int64

In [32]:
# Split the dataset
X3_train, X3_test, y3_train, y3_test = train_test_split(X3, y3, random_state=1)

In [33]:
X3_train.shape

(58152, 7)

In [34]:
X3_test.shape

(19384, 7)

In [35]:
# Create the StandardScaler instance
scaler3 = StandardScaler()
# Fit the Standard Scaler with the training data
X3_scaler = scaler3.fit(X_train)
# Scale the training data
X3_train_scaled = X3_scaler.transform(X3_train)
X3_test_scaled = X3_scaler.transform(X3_test)

In [36]:
# Instantiate the model with k = 3 neighbors
model = KNeighborsClassifier(n_neighbors=3)

In [37]:
# Train the model
model.fit(X3_train_scaled, y3_train)

KNeighborsClassifier(n_neighbors=3)

In [38]:
# Create predictions
y_pred = model.predict(X3_test_scaled)

# Review the predictions
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [39]:
# Print confusion matrix
confusion_matrix(y_pred,y_test)

array([[18092,   609],
       [  667,    16]], dtype=int64)

In [40]:
# Print classification report
print(classification_report(y_pred,y3_test))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00     18701
           1       0.93      0.84      0.88       683

    accuracy                           0.99     19384
   macro avg       0.96      0.92      0.94     19384
weighted avg       0.99      0.99      0.99     19384

